# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Michael Tran, Matthew Bocalon, Sisira Kadambat Nair
author_email: bhklab.jamesbannon@gmail.com
author_full_name: James Bannon
github_username: jbannon
has_additional_authors: true
project_description: Pipeline to create the Harmonized Drug Dataset (HDD)
project_name: HDD Data Pipelines
project_slug: hdd-data-pipeline
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
